version: "3.8"

services:
  web:
    build: . # Build the image using the Dockerfile in the current directory
    volumes:
      - .:/app # Mounts the local directory to /app in the container
    ports:
      - "8000:8000" # Maps port 8000 on the container to 8000 on the host
    environment:
      - ENV_FILE=.env # Loads environment variables from .env (if applicable)
    command:
      ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
